// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfLiSlnGJUlXNEiBOjkoPDQxoCE42Vlg',
    appId: '1:749387288681:web:83abb08fb52b9bc61512f8',
    messagingSenderId: '749387288681',
    projectId: 'tunckankilicsite-9f767',
    authDomain: 'tunckankilicsite-9f767.firebaseapp.com',
    storageBucket: 'tunckankilicsite-9f767.appspot.com',
    measurementId: 'G-ZWNECSSWWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1-ppdrfhUnCaSz3HRgy3koID0nfVyp4',
    appId: '1:749387288681:android:b8b64847f045c7321512f8',
    messagingSenderId: '749387288681',
    projectId: 'tunckankilicsite-9f767',
    storageBucket: 'tunckankilicsite-9f767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA53_Pb5byyVo8uy8us4g26_yO6J71x-og',
    appId: '1:749387288681:ios:3dd7d9e7663845fb1512f8',
    messagingSenderId: '749387288681',
    projectId: 'tunckankilicsite-9f767',
    storageBucket: 'tunckankilicsite-9f767.appspot.com',
    iosBundleId: 'site.tunckankilic.tunckankilic',
  );
}
